### ISSUE TITLE
negative view:sun_elevation

### ISSUE THREAD

**Issue by matthewhanson** [stactools-packages/aster#3]
This is a known issue, documented in the code, but there's no issue in stactools for it, see:
https://github.com/stactools-packages/aster/blob/main/src/stactools/aster/stac.py#L135

The v1.0.0 view extension allows for negative sun elevation angles now, so this can be updated.

**Comment by cuttlefish** [comment]
👍 
I think this gets resolved in #4 with https://github.com/stactools-packages/aster/blob/be0739c49c70ab01e372d1c15e55094cd6e00c1b/src/stactools/aster/stac.py#L138-L142
Does that look correct?

**Comment by matthewhanson** [comment]
Yep, looks all good now
